### ISSUE TITLE
Ranged Attack and Curing getting locked out

### ISSUE THREAD

**Issue by Raycian** [ExodusFFXI/Exodus#15]
**_I have:_**

- [ ] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [ ] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**

**_Server Version_** (type `@revision` in game) **:**

**_Source Branch_** (master/stable) **:**

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

I am getting locked out on actions. Ranged attack sometimes wont let me use it, saying "Tadeo cannot perform that action". Lets me again after I engage and melee. Peanut will sometimes get locked out on curing giving the same message. That one goes away on zoning.

**Comment by Alice5150** [comment]
This is fixed in our next update.

**Comment by Alice5150** [comment]
Unable to recreate issue, though is reported to still exist. However, I believe it was an intentional change by DSP to prevent excessive powerleveling.
