### ISSUE TITLE
No exp if cured outside of PT

### ISSUE THREAD

**Issue by Raycian** [ExodusFFXI/Exodus#16]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**

**_Server Version_** (type `@revision` in game) **:**

**_Source Branch_** (master/stable) **:**

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

No exp gained if cured from outside of the party. I thought that it may have just been me in Gusgen but Deathgirl confirmed in Discord that it was happening to him as well.

**Comment by Alice5150** [comment]
Fixed in next update as well.

**Comment by Alice5150** [comment]
I believe this to be an intentional change by DSP to prevent excessive power-leveling.
